
services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: PaymentModule
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: backend_app
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_APPLICATION_NAME: backend-tutorial
      SERVER_PORT: 3000
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/PaymentModule
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345678
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
    ports:
      - "3000:3000"
